const HomeProduct =
    [
        {
            id: 1,
            Name: 'product1',
            price: '26',
            image: 'image/image/p1.webp',
            cat: 'tv',
            type: 'new',
        },
        {
            id: 2,
            Name: 'product2',
            price: '96',
            image: 'image/image/p2.webp',
            cat: 'laptop',
            type: 'new',
        },
        {
            id: 3,
            Name: 'product3',
            price: '87',
            image: 'image/image/p3.webp',
            cat: 'watch',
            type: 'new',
        },
        {
            id: 4,
            Name: 'product4',
            price: '47',
            image: 'image/image/p4.webp',
            cat: 'speaker',
            type: 'featured',
        },
        {
            id: 5,
            Name: 'product5',
            price: '37',
            image: 'image/image/p5.webp',
            cat: 'speaker',
            type: 'featured',
        },
        {
            id: 6,
            Name: 'product6',
            price: '55',
            image: 'image/image/p6.webp',
            cat: 'phone',
            type: 'top',
        },
        {
            id: 7,
            Name: 'product7',
            price: '77',
            image: 'image/image/p7.webp',
            cat: 'headphone',
            type: 'top',
        },
        {
            id: 8,
            Name: 'product8',
            price: '87',
            image: 'image/image/p8.webp',
            cat: 'electronics',
            type: 'top',
        },
        {
            id: 9,
            Name: 'product9',
            price: '97',
            image: 'image/image/p9.jpg',
            cat: 'phone',
            type: 'new',
        },
        {
            id: 10,
            Name: 'product 10',
            price: '69',
            image: 'image/image/p10.jpg',
            cat: 'headphone',
            type: 'featured',
        },
        {
            id: 11,
            Name: 'product 11',
            price: '85',
            image: 'image/image/p11.jpg',
            cat: 'electronics',
            type: 'top',
        },
        {
            id: 12,
            Name: 'product 12',
            price: '54',
            image: 'image/image/p12.jpg',
            cat: 'speaker',
            type: 'top',
        },
    ]

export default HomeProduct